export const SET_IS_LOGIN = "set_is_login";
export const SET_USER_INFO = "set_user_info";
export const ADD_TO_CART = "add_to_cart";
export const REMOVE_FROM_CART = "remove_from_cart";
export const UPDATE_CART_QUANTITY = "update_cart_quantity";
export const CLEAR_CART = "clear_cart";
export const SET_PRODUCTS = "set_products";
export const SET_CATEGORIES = "set_categories"; // Mới
export const SET_CART = "set_cart";